name: Simple CI

on:
  workflow_dispatch:
    inputs:
      left:
        description: "Left integer value"
        required: true
        default: "5"
      right:
        description: "Right integer value"
        required: true
        default: "2"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip'
      
      - name: Install Ruff dependencies
        run: |
          pip install -r requirements-lint.txt
      
      - name: Run Ruff
        run: |
          ruff check . | tee ruff.txt
      
      - name: Add Ruff summary
        if: always()
        run: |
          echo "## Ruff Lint results" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          cat ruff.txt >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
  test:
    runs-on: ubuntu-latest
    # needs: lint
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip'
      
      - name: Install test dependencies
        run: |
          pip install -r requirements.txt
          pip install -r requirements-test.txt
          pip install -e .
      
      - name: Run tests with coverage
        run: |
          pytest --cov=app --cov-report=term | tee pytest.txt
      
      - name: Add coverage summary
        if: always()
        run: |
          echo "## Test Coverage" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          cat pytest.txt >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
         
  docker-build:
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
      - uses: actions/checkout@v4
      
      - name: Build docker image
        run: docker build -t simple-web-app:${{ github.sha }} .

      - name: Run container
        run: |
          docker run -d -p 8000:8000 --name test-container simple-web-app:${{ github.sha }}
          for i in {1..5}; do
            if curl -s "http://localhost:8000/health"; then
              echo -e '\nApp is up'
              exit 0
            fi
            sleep 3
          done
          echo -e 'App failed to start'
          docker logs test-container
          exit 1
      
      - name: Call /add endpoint
        id: call_api
        run: |
          LEFT=${{ github.event.inputs.left }}
          RIGHT=${{ github.event.inputs.right }}
          RESPONSE=$(curl -s "http://localhost:8000/add?left=${LEFT}&right=${RIGHT}")
          echo "response=$RESPONSE" >> $GITHUB_OUTPUT
      
      - name: Add result to summary
        run: |
          echo "## Web App Smoke Test" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          echo "Input parameters" >> $GITHUB_STEP_SUMMARY
          echo "Left: ${{ github.event.inputs.left }}" >> $GITHUB_STEP_SUMMARY
          echo "Right: ${{ github.event.inputs.right }}" >> $GITHUB_STEP_SUMMARY
          echo "Result: ${{ steps.call_api.outputs.response }}" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
  trivy-scan:
    runs-on: ubuntu-latest
    needs: docker-build
    steps:
      - name: Scan Docker image with Trivy
        uses: aquasecurity/trivy-action@v2
        with:
          scan-type: image
          image-ref: simple-web-app:${{ github.sha }}
          format: table
          exit-code: 1
          severity: CRITICAL,HIGH
